version: '3.8'

services:
  eureka-service:
    image: eureka-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=eureka-service
      - SERVER_PORT=8761
      - EUREKA_INSTANCE_HOSTNAME=localhost
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://localhost:8761/eureka/
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=5
      - EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=10
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true