FROM openjdk:17-jdk-alpine
MAINTAINER Laécio
COPY target/eureka-service-0.0.1-SNAPSHOT.jar eureka-service-0.0.1-SNAPSHOT.jar
EXPOSE 8761
ENTRYPOINT ["java","-jar","/eureka-service-0.0.1-SNAPSHOT.jar"]
#docker run -p8761:8761 eureka-service:latest